// flow-typed signature: 9af52d599c3f81a63c6a009453f66aa7
// flow-typed version: <<STUB>>/gulp.spritesmith_v^6.9.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp.spritesmith'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp.spritesmith' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp.spritesmith/docs/gulpfile' {
  declare module.exports: any;
}

declare module 'gulp.spritesmith/lib/gulp-spritesmith' {
  declare module.exports: any;
}

declare module 'gulp.spritesmith/test/gulp-spritesmith_test' {
  declare module.exports: any;
}

declare module 'gulp.spritesmith/test/gulpfile' {
  declare module.exports: any;
}

declare module 'gulp.spritesmith/test/utils/child' {
  declare module.exports: any;
}

declare module 'gulp.spritesmith/test/utils/image' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp.spritesmith/docs/gulpfile.js' {
  declare module.exports: $Exports<'gulp.spritesmith/docs/gulpfile'>;
}
declare module 'gulp.spritesmith/lib/gulp-spritesmith.js' {
  declare module.exports: $Exports<'gulp.spritesmith/lib/gulp-spritesmith'>;
}
declare module 'gulp.spritesmith/test/gulp-spritesmith_test.js' {
  declare module.exports: $Exports<'gulp.spritesmith/test/gulp-spritesmith_test'>;
}
declare module 'gulp.spritesmith/test/gulpfile.js' {
  declare module.exports: $Exports<'gulp.spritesmith/test/gulpfile'>;
}
declare module 'gulp.spritesmith/test/utils/child.js' {
  declare module.exports: $Exports<'gulp.spritesmith/test/utils/child'>;
}
declare module 'gulp.spritesmith/test/utils/image.js' {
  declare module.exports: $Exports<'gulp.spritesmith/test/utils/image'>;
}
