// flow-typed signature: 7ae991ce83bf00e3a78780272b0cb06a
// flow-typed version: <<STUB>>/habitica_v^4.0.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'habitica'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'habitica' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'habitica/lib/connection' {
  declare module.exports: any;
}

declare module 'habitica/lib/errors' {
  declare module.exports: any;
}

// Filename aliases
declare module 'habitica/index' {
  declare module.exports: $Exports<'habitica'>;
}
declare module 'habitica/index.js' {
  declare module.exports: $Exports<'habitica'>;
}
declare module 'habitica/lib/connection.js' {
  declare module.exports: $Exports<'habitica/lib/connection'>;
}
declare module 'habitica/lib/errors.js' {
  declare module.exports: $Exports<'habitica/lib/errors'>;
}
