// flow-typed signature: f53915139ad62134f3712220607bd93e
// flow-typed version: <<STUB>>/normalize-css_v^2.3.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'normalize-css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'normalize-css' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'normalize-css/normalize' {
  declare module.exports: any;
}

// Filename aliases
declare module 'normalize-css/index' {
  declare module.exports: $Exports<'normalize-css'>;
}
declare module 'normalize-css/index.js' {
  declare module.exports: $Exports<'normalize-css'>;
}
declare module 'normalize-css/normalize.js' {
  declare module.exports: $Exports<'normalize-css/normalize'>;
}
