// flow-typed signature: 32db902bcba50188383c902efdbc17bc
// flow-typed version: <<STUB>>/react-progressbar_v^15.4.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-progressbar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-progressbar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-progressbar/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-progressbar/lib/index.js' {
  declare module.exports: $Exports<'react-progressbar/lib/index'>;
}
